# @package agent
_target_: my_agent.agent.IJEPAPlanningAgent # Path to your class
mlp_weights_path: null # Set to path/to/your/pretrained/mlp.pth if needed, or null for training from scratch
ijepa_model_id: facebook/ijepa_vith14_1k # The I-JEPA model ID
trajectory_sampling:
  _target_: navsim.common.trajectory_sampling.TrajectorySampling # Adjust path if needed
  time_horizon: 4.0
  interval_length: 0.5
  num_history_frames: 4 # Needed by TrajectoryTargetBuilderGT
use_cls_token_if_available: true
requires_scene: false # Adjust if your agent needs scene data beyond current frame
learning_rate: 0.0001 # Configurable learning rate
loss_criterion: l1 # 'l1' or 'mse'
# Any other parameters needed by your agent's __init__